### ISSUE TITLE
I want add, another JDBC

### ISSUE THREAD

**Issue by dumy** [Hitachi/node-red-contrib-jdbc#4]
Hello

It's possible add another JDBC exe: Informix, DB2 or another ?

Where add JDBC from another location ? 

![image](https://user-images.githubusercontent.com/8275027/143402602-6629f522-b282-446b-941d-c990f84bea67.png)

**Comment by kazuhitoyokoi** [comment]
@dumy Yes, as the implementation, this JDBC node can also access other databases via the JDBC driver. JDBC driver file should be specified by the file path. I recommend the Ubuntu environment to use this node because I cannot reproduce the problem.

**Comment by dumy** [comment]
`
-----------------------------------------------------------
2021-11-26T09:53:35.594Z Install : node-red-contrib-jdbc 0.1.2

2021-11-26T09:53:13.803Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-jdbc@0.1.2
2021-11-26T09:53:24.135Z [err] npm
2021-11-26T09:53:24.135Z [err]  ERR! code 1
2021-11-26T09:53:24.135Z [err] npm ERR! path /home/sabd/.node-red/node_modules/java
2021-11-26T09:53:24.143Z [err] npm ERR!
2021-11-26T09:53:24.143Z [err]  command failed
2021-11-26T09:53:24.143Z [err] npm ERR! command sh -c node-gyp rebuild
2021-11-26T09:53:24.143Z [err] npm ERR! gyp info it worked if it ends with ok
2021-11-26T09:53:24.143Z [err] npm ERR! gyp info using node-gyp@8.2.0
2021-11-26T09:53:24.143Z [err] npm ERR! gyp info using node@16.13.0 | linux | x64
2021-11-26T09:53:24.143Z [err] npm ERR!
2021-11-26T09:53:24.144Z [err]  gyp ERR! find Python 
2021-11-26T09:53:24.144Z [err] npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
2021-11-26T09:53:24.144Z [err] npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2021-11-26T09:53:24.144Z [err] npm ERR!
2021-11-26T09:53:24.144Z [err]  gyp ERR! find Python checking if "python3" can be used
2021-11-26T09:53:24.144Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2021-11-26T09:53:24.144Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2021-11-26T09:53:24.144Z [err] npm ERR! gyp ERR! find Python - executable path is "/usr/bin/python"
2021-11-26T09:53:24.144Z [err] npm
2021-11-26T09:53:24.144Z [err]  ERR! gyp ERR! find Python - version is "2.7.5"
2021-11-26T09:53:24.144Z [err] npm ERR! gyp ERR! find Python - version is 2.7.5 - should be >=3.6.0
2021-11-26T09:53:24.144Z [err] npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
2021-11-26T09:53:24.144Z [err] npm ERR!
2021-11-26T09:53:24.144Z [err]  gyp ERR! find Python 
2021-11-26T09:53:24.144Z [err] npm ERR! gyp ERR! find Python **********************************************************
2021-11-26T09:53:24.144Z [err] npm ERR! gyp ERR! find Python You need to install the latest version of Python.
2021-11-26T09:53:24.144Z [err] npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2021-11-26T09:53:24.144Z [err] npm
2021-11-26T09:53:24.145Z [err]  ERR! gyp ERR! find Python you can try one of the following options:
2021-11-26T09:53:24.145Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2021-11-26T09:53:24.145Z [err] npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2021-11-26T09:53:24.145Z [err] npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
2021-11-26T09:53:24.145Z [err] npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
2021-11-26T09:53:24.145Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2021-11-26T09:53:24.145Z [err] npm ERR! gyp ERR! find Python For more information consult the documentation at:
2021-11-26T09:53:24.145Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2021-11-26T09:53:24.145Z [err] npm ERR! gyp ERR! find Python **********************************************************
2021-11-26T09:53:24.145Z [err] npm
2021-11-26T09:53:24.146Z [err]  ERR! gyp ERR! find Python 
2021-11-26T09:53:24.146Z [err] npm ERR! gyp ERR! configure error 
2021-11-26T09:53:24.146Z [err] npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
2021-11-26T09:53:24.146Z [err] npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2021-11-26T09:53:24.146Z [err] npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2021-11-26T09:53:24.146Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:266:16)
2021-11-26T09:53:24.146Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:297:7)
2021-11-26T09:53:24.146Z [err] npm
2021-11-26T09:53:24.146Z [err]  ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:388:7)
2021-11-26T09:53:24.146Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
2021-11-26T09:53:24.146Z [err] npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
2021-11-26T09:53:24.146Z [err] npm
2021-11-26T09:53:24.146Z [err]  ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
2021-11-26T09:53:24.146Z [err] npm ERR! gyp ERR! System Linux 3.10.0-693.17.1.el7.x86_64
2021-11-26T09:53:24.146Z [err] npm ERR!
2021-11-26T09:53:24.147Z [err]  gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2021-11-26T09:53:24.147Z [err] npm ERR! gyp ERR! cwd /home/sabd/.node-red/node_modules/java
2021-11-26T09:53:24.147Z [err] npm ERR!
2021-11-26T09:53:24.147Z [err]  gyp ERR! node -v v16.13.0
2021-11-26T09:53:24.147Z [err] npm ERR! gyp ERR! node-gyp -v v8.2.0
2021-11-26T09:53:24.147Z [err] npm ERR! gyp ERR! not ok
2021-11-26T09:53:24.172Z [err] 
2021-11-26T09:53:24.173Z [err] npm ERR! A complete log of this run can be found in:
2021-11-26T09:53:24.173Z [err] npm ERR!     /home/sabd/.npm/_logs/2021-11-26T09_53_24_151Z-debug.log
2021-11-26T09:53:24.209Z rc=1`

It's error when install this node

**Comment by kazuhitoyokoi** [comment]
@dumy Thank you for your reporting about the error on the Linux environment. This problem seems to occur due to the lack of python. Could you install python in your environment?

**Comment by dumy** [comment]
> @dumy ‎Vă mulțumim pentru raportarea despre eroarea pe mediul Linux. Această problemă pare să apară din cauza lipsei de python. Ați putea instala Python în mediul dvs.?‎

Ok, thx I am to trie to install python
