### ISSUE TITLE
No suitable driver found

### ISSUE THREAD

**Issue by toddwarrington** [Hitachi/node-red-contrib-jdbc#5]
I keep getting this error "Error running static method java.sql.SQLException: No suitable driver found for jdbc:as400:..." when I deploy my flow using this jdbc node.  Can you please give me some insight as to where I need to put the .jar file for my driver?

**Comment by kazuhitoyokoi** [comment]
Thank you for using our JDBC node. You need to put the jar file on the current directory and execute the Node-RED command from the current directory.

**Comment by toddwarrington** [comment]
K,

I manually started node-red from the directory that contains the jar file and the error is still the same.  Here’s the complete log file information:

16 Mar 11:08:27 - [error] [jdbc:database] Error: Error running static method
java.sql.SQLException: No suitable driver found for jdbc:as400://10.10.0.7/
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)

    at Object.getConnectionSync (/home/installer/.node-red/node_modules/jdbc/lib/drivermanager.js:76:38)
    at addConnectionSync (/home/installer/.node-red/node_modules/jdbc/lib/pool.js:50:17)
    at JDBC.Pool.reserve (/home/installer/.node-red/node_modules/jdbc/lib/pool.js:192:14)
    at Function node setup:ddab20e1673dc436 [database]:29:4
    at Function node setup:ddab20e1673dc436 [database]:40:23
    at Script.runInContext (vm.js:144:12)
    at ***@***.******@***.***/nodes/core/function/10-function.js:392:41>

Suggestions?
